export enum MessageHeaders {
    CONNECTED_PING = 0x00,
    UNCONNECTED_PING = 0x01,
    UNCONNECTED_PONG = 0x1c,
    CONNECTED_PONG = 0x03,
    OPEN_CONNECTION_REQUEST_1 = 0x05,
    OPEN_CONNECTION_REPLY_1 = 0x06,
    OPEN_CONNECTION_REQUEST_2 = 0x07,
    OPEN_CONNECTION_REPLY_2 = 0x08,
    CONNECTION_REQUEST = 0x09,
    CONNECTION_REQUEST_ACCEPTED = 0x10,
    NEW_INCOMING_CONNECTION = 0x13,
    DISCONNECT_NOTIFICATION = 0x15,
    INCOMPATIBLE_PROTOCOL_VERSION = 0x19,

    ACKNOWLEDGE_PACKET = 0xc0,
    NACKNOWLEDGE_PACKET = 0xa0,
    QUERY = 0xfe
}
export default MessageHeaders;
