/**
 * Derives JSPrismarine's own block state catalogue from a captured Bedrock server.
 *
 * Run with `pnpm generate:blocks`. The source and the destination are in
 * `datagen/manifest.json`; nothing here decides either.
 *
 * The input used to be `canonical_block_states.nbt`, a third party dump extracted with a
 * native mod hooking the server binary - the one leg of the extraction still leaning on
 * somebody else. It is now `snapshot/block-palette.json`, captured from a Bedrock Dedicated
 * Server directly. `datagen/README-palette.md` says how.
 *
 * What comes out is a description of *which properties each block has and which values they
 * accept* - not an ordered palette. Runtime ids are hashes computed from a block's own name
 * and state, so nothing here depends on the client's internal ordering, and a plugin can add
 * blocks without disturbing any of these.
 */
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const HERE = path.dirname(new URL(import.meta.url).pathname);
const manifest = JSON.parse(fs.readFileSync(path.join(HERE, 'manifest.json'), 'utf8'));

/**
 * A value's type, as the catalogue names it.
 *
 * The capture carries JavaScript values, and the three the protocol has map onto them one to
 * one. A boolean is a `byte` rather than a type of its own, which is what the wire has and
 * what the hash is computed over - `true` and `1` are not interchangeable there.
 */
const typeOf = (value) => {
    if (typeof value === 'boolean') return 'byte';
    if (typeof value === 'number') return 'int';
    if (typeof value === 'string') return 'string';

    throw new Error(`No block state type for ${typeof value}`);
};

/** Booleans travel as 0 and 1; everything else is already what it will be. */
const toWire = (value) => (typeof value === 'boolean' ? Number(value) : value);

const source = path.resolve(HERE, manifest.blocks.source);
if (!fs.existsSync(source)) {
    console.error(
        `Missing ${source}. It is captured from a Bedrock Dedicated Server - see ` +
            `datagen/README-palette.md, which is also what to follow to refresh it for a new version.`
    );
    process.exit(1);
}

const capture = JSON.parse(fs.readFileSync(source, 'utf8'));

const blocks = {};
let stateCount = 0;

/**
 * The two halves, joined by the rule that separates them.
 *
 * Which properties a block has comes from `states` - the saved world, which stores what the
 * network carries. Which values each takes comes from `domains` - the game, asked block by
 * block. Taking the property list from the game instead would add the legacy properties a
 * flattened block still answers for, and every state built on one hashes to a runtime id no
 * client recognises.
 */
for (const [name, states] of Object.entries(capture.states).sort(([a], [b]) => a.localeCompare(b))) {
    const domains = capture.domains[name];
    if (domains === undefined) throw new Error(`${name} was saved to the world but the game did not describe it`);

    const properties = {};
    let permutations = 1;

    for (const property of Object.keys(states).sort()) {
        const domain = domains[property];
        if (domain === undefined)
            throw new Error(`${name} carries ${property} on the wire but the game has no values for it`);

        properties[property] = {
            type: typeOf(domain.default),
            values: domain.values.map(toWire),
            default: toWire(domain.default)
        };

        permutations *= domain.values.length;
    }

    blocks[name] = { properties };
    stateCount += permutations;
}

const output = {
    $comment:
        'Generated by packages/minecraft/datagen/generate-blocks.js - do not edit. Change the ' +
        'manifest and run `pnpm generate:blocks`. Runtime ids are hashes of name+states, so this ' +
        'describes what each block accepts; it is not an ordered palette and nothing depends on ' +
        'the order of these keys.',
    source: path.basename(source),
    minecraftVersion: capture.minecraftVersion,
    blockCount: Object.keys(blocks).length,
    stateCount,
    blocks
};

const target = path.resolve(HERE, manifest.blocks.target);
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, `${JSON.stringify(output, null, 2)}\n`);

console.log(`Wrote ${path.relative(process.cwd(), target)}`);
console.log(`  ${output.blockCount} blocks, ${stateCount} states, from ${capture.server}`);
