export enum RakNetIdentifiers {
    CONNECTED_PING = 0x00,
    UNCONNECTED_PING = 0x01,
    UNCONNECTED_PONG = 0x1C,
    CONNECTED_PONG = 0x03,
    OPEN_CONNECTION_REQUEST_1 = 0x05,
    OPEN_CONNECTION_REPLY_1 = 0x06,
    OPEN_CONNECTION_REQUEST_2 = 0x07,
    OPEN_CONNECTION_REPLY_2 = 0x08
}
