name: ðŸ“¦ Install
description: Install dependencies

runs:
    using: 'composite'
    steps:
        - name: ðŸŽï¸ Setup Node
          uses: actions/setup-node@v6
          with:
              registry-url: 'https://registry.npmjs.org/'
              node-version-file: '.nvmrc'

        - name: ðŸŽï¸ Setup pnpm
          uses: pnpm/action-setup@v4
          with:
              run_install: false

        - name: ðŸŽï¸ Setup Bun
          uses: oven-sh/setup-bun@v2
          with:
              bun-version: canary

        - name: Get pnpm store directory
          shell: bash
          run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

        - uses: actions/cache@v4
          name: Setup pnpm cache
          with:
              path: ${{ env.STORE_PATH }}
              key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: ${{ runner.os }}-pnpm-store-

        - name: Install dependencies
          shell: bash
          run: pnpm install
