name: Generate Documentations
on:
    workflow_run:
        workflows: ['Linting']
        types: [completed]
        branches: [master]

jobs:
    build-and-publish-docs:
        name: 📖 Build and Publish Docs
        runs-on: ubuntu-latest
        if: github.event.workflow_run.conclusion == 'success'
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        steps:
            - uses: actions/checkout@v5
              with:
                  submodules: 'recursive'

            - name: 📦 Install
              uses: ./.github/common/install

            - run: pnpm run build
            - run: pnpm run build:docs

            - uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
                  enable_jekyll: false
                  cname: 'docs.jsprismarine.org'
                  commit_message: ${{ github.event.workflow_run.head_commit.message }}
