name: Linting
on:
    push:
    pull_request:

jobs:
    lint:
        name: 📃 Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
              with:
                  submodules: 'recursive'

            - name: 📦 Install
              uses: ./.github/common/install

            - name: 📃 Lint
              run: pnpm run lint

