name: Publish to GitHub Registry
on:
    release:
        types: [created]
    workflow_dispatch:

env:
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    
jobs:
    publish:
      runs-on: ubuntu-latest
      permissions:
          contents: read
          packages: write
      steps:
          - uses: actions/checkout@v4

          - name: 📦 Install
            uses: ./.github/common/install

          - run: pnpm run build

          - run: |
                echo @jsprismarine:https://npm.pkg.github.com/ > .npmrc
                echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> ~/.npmrc

          - run: npm publish --workspaces
            env:
                NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
