name: Release

on:
    push:
        branches:
            - master

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}

env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions: write-all

jobs:
    release:
        name: 🚚 Release
        runs-on: ubuntu-latest
        steps:
            - name: 🕶️ Checkout repository
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0
                  submodules: 'recursive'

            - name: 📦 Install
              uses: ./.github/common/install

            - name: 🔨 Build
              run: pnpm run build

            - name: 🤝 Create Release Pull Request or Publish to NPM
              id: changesets
              uses: changesets/action@v1
              with:
                  createGithubReleases: true
                  version: pnpm run version
                  publish: pnpm run release
                  setupGitUser: false
                  commit: |
                      Changeset: Increment package & dependecy versions.

                      Congratulations on the new release! 🎉
                      This is an automated commit triggered by the `release` workflow.
                  title: 🚀 Release packages

            - name: 🫨 Create Unstable Release
              if: steps.changesets.outputs.published != 'true'
              run: |
                  git checkout master
                  pnpm run version:unstable
                  pnpm run release:unstable
